{
  "throws": "Cannot use `catch` or `finally` with error-coalescing `try` (1:8)"
}
