a! catch err:
  | SpecificError: specificAnswer
  | Error: generalAnswer
